properties([disableConcurrentBuilds()])

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    
    stages {
        stage("Creating Docker Image") {
            steps {
                dir ('Jenkins') {
                    sh 'docker build -t wireflex/jenkins:1 . '
                }
            }
        }
        stage("DockerHub Login and Push") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_wireflex', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                    sh 'docker push wireflex/jenkins:1'
                }
            }
        }
        stage("Mutnaya hrenovina") {
            steps {
                    sh """ssh root@94.142.141.77 'cd ~ && ls -la'
                    cd ~ && cat << 'EOF' > docker-compose.yml 
services:
  test:
    image: wireflex/jenkins:1
    ports:
      - '80:80'
    restart: unless-stopped
EOF"""
                    sh 'cd ~ && sudo cp docker-compose.yml docker-compose.yaml'
                    sh 'cd ~ && scp -i ~/.ssh/id_rsa docker-compose.yaml  root@94.142.141.77:/root'
              }
         }
        stage("Deploying at Production server") {
            steps {
                    sh "ssh root@94.142.141.77 'cd ~ && docker compose down'"
                    sh "ssh root@94.142.141.77 'cd ~ && docker system prune'" 
                    sh "ssh root@94.142.141.77 'cd ~ && docker compose up -d'"
            }
        }
    }
} 
