#!groovy
// Run docker build
properties([disableConcurrentBuilds()])

pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        timestamps()
    }
    stages {
        stage("docker login") {
            steps {
                echo " ============== docker login and push =================="
                withCredentials([usernamePassword(credentialsId: 'dockerhub_wireflex', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                    sh 'docker push wireflex/test'
                }
            }
        }
        stage("create docker image") {
            steps {
                echo " ============== start building image =================="
                dir ('Jenkins') {
                	sh 'docker build -t wireflex/test . '
               }
           }
        }
    stage("pizdec") {
           steps {
                echo " ============== start pizdec =================="
                sh 'cp docker-compose.yml docker-compose.yaml'
                sh 'scp -i ~/.ssh/id_rsa docker-compose.yaml  root@94.142.141.77:/root'
              }
         }
    }
    stage('Deploy on Remote Server') {
            steps {
            echo " Connect to production and deploy"
                     sh "ssh root@94.142.141.77 'docker compose down'"
                     sh "ssh root@94.142.141.77 'docker compose up -d'"
                }
            }
        }
