---
- name: Deploy on remote servers
  hosts: all
  tasks:
  - name: Stop existing containers
    command: docker compose down

  - name: Delete useless images
    command: echo "y" | docker system prune -a

  - name: Start containers
    command: docker compose up -d
